---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpdevops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: ingressdns
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingressdns
  namespace: default
subjects:
- kind: ServiceAccount
  name: cpdevops
  namespace: default
roleRef:
  kind: ClusterRole
  name: ingressdns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ingressdns
  name: ingressdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingressdns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingressdns
    spec:
      serviceAccountName: cpdevops
      containers:
      - image: 10.99.88.14:5000/ingressdns
        imagePullPolicy: Always
        name: ingressdns